version: '3.7'
services:
  app:
    container_name: fastify-app
    restart: always
    build: .
    image: 'fastify-app:1.0.0'
    ports:
      - '3000:3000'
    expose:
      - '3000'
    links:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    container_name: fastify-app-mongodb
    ports:
      - '27018:27017'
    expose:
      - '27018'
    environment:
      MONGODB_USER: ''
      MONGODB_PASSWORD: ''
